-- |
-- Module      : Example.Structured
-- Description : Model-generated JSON decoded into typed Haskell data.
--
-- 'structuredProgram' shows the normal authoring path: 'deriveSchema' derives
-- the carried schema, witness, and total conversion from the record declaration.
-- Execution accepts only matching JSON; 'consumeModelJson' decodes the same
-- bytes directly into the ordinary Haskell record.
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QualifiedDo #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE RebindableSyntax #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}

module Example.Structured
  ( structuredProgram,
    structuredBlurb,
    structuredHelp,
    structuredScript,
    ReleasePlan (..),
    consumeModelJson,
    summarizeReleasePlan,
    structuredAnswer,
  )
where

import Agentic.Schema.Json (decodeAs)
import Agentic.Schema.TH (deriveSchema)
import Agentic.Workflow
import qualified Agentic.Workflow.Do as W
import Data.String (fromString)
import Data.Text (Text)
import qualified Data.Text as T
import Prelude

data ReleasePlan = ReleasePlan
  { title :: Text,
    priority :: Integer,
    steps :: [Text]
  }
  deriving (Eq, Show)

$(deriveSchema ''ReleasePlan)

consumeModelJson :: Text -> Maybe ReleasePlan
consumeModelJson = decodeAs @ReleasePlan

summarizeReleasePlan :: ReleasePlan -> Text
summarizeReleasePlan plan =
  title plan
    <> " (priority "
    <> T.pack (show (priority plan))
    <> "): "
    <> T.intercalate "; " (steps plan)

producerBrief :: Text
producerBrief =
  [wft|
  Produce a small release plan with concise, actionable steps. Reply only in
  the structured format requested by the attached schema.|]

-- | A model question whose answer schema is derived from 'ReleasePlan'.
structuredProgram :: Program
structuredProgram = workflow W.do
  _plan <-
    ask (model "structured-producer") [wf|{producerBrief}|]
      `annotated` (structured @ReleasePlan)
  stop

structuredAnswer :: Text
structuredAnswer =
  "{\"title\":\"Ship structured answers\",\"priority\":1,\"steps\":[\"decode JSON\",\"consume typed fields\"]}"

structuredScript :: [(Text, Text)]
structuredScript = [(producerBrief, structuredAnswer)]

structuredBlurb :: Text
structuredBlurb = "model JSON validated by a schema and consumed as typed Haskell data"

structuredHelp :: Text
structuredHelp =
  [wft|
  A deliberately small structured-answer example. The model returns a JSON
  object under a schema derived mechanically from `ReleasePlan`; agent-cat
  validates it and `consumeModelJson` decodes it directly into that record.
  `summarizeReleasePlan` then consumes all fields.

  **Inputs.** none.

  **Transport.** Any model transport. The runtime appends the generated JSON
  Schema to the question and re-asks when the model returns malformed or
  schema-mismatched JSON.

  ```sh
  agentic-run run structured --engine acp --adapter claude
  ```

  **Rehearsal.** The canned reply is a complete release-plan object, so the
  normal workflow decoder is exercised without a network:

  ```sh
  agentic-run run structured --scripted
  ```

  **Caveats.** The analyzable workflow records the typed answer and stops; it
  does not add a dynamic record-projection primitive. The schema declaration,
  witness, and nested-product conversion are all generated by the one
  `deriveSchema ''ReleasePlan` splice above.
  |]
