{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}

module Example.StructuredInfo
  ( structuredBlurb,
    structuredResultBlurb,
    structuredHelp,
    structuredResultHelp,
    structuredScript,
    structuredAnswer,
  )
where

import Agentic.Workflow (wft)
import Data.Text (Text)
import Structured (producerBrief)

structuredAnswer :: Text
structuredAnswer =
  "{\"title\":\"Ship structured answers\",\"priority\":1,\"steps\":[\"decode JSON\",\"consume typed fields\"]}"

structuredScript :: [(Text, Text)]
structuredScript = [(producerBrief, structuredAnswer)]

structuredBlurb :: Text
structuredBlurb = "model JSON validated by a schema and consumed as typed Haskell data"

structuredResultBlurb :: Text
structuredResultBlurb = "a schema-validated model answer returned as the whole program's typed result"

structuredHelp :: Text
structuredHelp =
  [wft|
  A deliberately small structured-answer example. The model returns a JSON
  object under a schema derived mechanically from `ReleasePlan`; agent-cat
  validates it and `consumeModelJson` decodes it directly into that record.
  `summarizeReleasePlan` then consumes all fields.

  **Inputs.** none.

  **Transport.** Any model transport. The runtime appends the generated JSON
  Schema to the question and re-asks when the model returns malformed or
  schema-mismatched JSON.

  ```sh
  agentic-run run structured --engine acp --adapter claude
  ```

  **Rehearsal.** The canned reply is a complete release-plan object, so the
  normal workflow decoder is exercised without a network:

  ```sh
  agentic-run run structured --scripted
  ```

  **Caveats.** The analyzable workflow records the typed answer and stops; it
  does not add a dynamic record-projection primitive. The schema declaration,
  witness, and nested-product conversion are all generated by the one
  `deriveSchema ''ReleasePlan` splice above.
  |]

structuredResultHelp :: Text
structuredResultHelp =
  [wft|
  A result-bearing variant of `structured`: one schema-validated model answer
  becomes the closed program's result instead of being discarded at `stop`.
  The result witness is the same schema the question was decoded against.

  **Inputs.** none.

  **Transport.** Any model transport. The result is rendered after the trace
  from the already-decoded structured value; rendering asks nobody again.

  ```sh
  agentic-run run structured-result --engine acp --adapter claude
  ```

  **Rehearsal.** The same complete canned object as `structured`, returned from
  the program and rendered after the trace:

  ```sh
  agentic-run run structured-result --scripted
  ```

  **Caveats.** A result changes no question, branch, path or bill. The legacy
  `structured` row remains receipt-valued so its frozen behavior does not move.
  |]
