import Agentic.Monoid
import Agentic.Semiring
import Mathlib.Algebra.FreeMonoid.Basic
import Mathlib.GroupTheory.Congruence.Defs

/-!
# Mazurkiewicz traces and sessions

A workflow's history is a *sequence* of turns, but not every reordering of
that sequence is a different history: a panel of reviewers consulted
concurrently may be consulted in any order, while the stages of a pipeline may
not. This module builds the object in which that distinction is an *equality*
rather than a side condition — the free partially commutative monoid on an
alphabet of turns, quotiented by an independence relation.

The quotient is genuine: two independent schedules are *the same trace*, not
two lists carrying a predicate that happens to relate them. What is no longer
hand-rolled is the *machinery* of the quotient. Mathlib has the free monoid
(`FreeMonoid A`, a synonym for `List A` with `*` given by `++`) and it has the
quotient of a monoid by a generated congruence (`conGen`, `Con.Quotient`,
`Con.monoid`, `Con.eq`). A Mazurkiewicz trace monoid is exactly the second
applied to the first, so that is how it is built here: the package no longer
generates its own equivalence, proves `append` congruent on both sides, lifts
concatenation through two nested `Quot.lift`s, or transports the three monoid
laws by `Quot.inductionOn`. All of that is Mathlib's, and the only thing this
module supplies is `Swap` — which pairs of adjacent turns may be exchanged.

**Survivor, and what Mathlib lacks.** Mathlib has no trace (Mazurkiewicz,
partially commutative) monoid: `FreeMonoid`, `Con` and `conGen` are the parts,
and nothing assembles them into this object or proves anything about
independence. `Swap`, `Trace`, and the two exactness theorems at the end are
therefore ours; the quotient algebra is not.

A session is then a semiring-valued judgment of every history, and the
Brzozowski derivative is the act of continuing a session past a prefix.

The trace monoid is stated once, as the package's `PMonoid` (`Agentic.Monoid`),
and not a second time as bespoke `Mul`/`One` instances with their own three
law theorems. That also settles the module's place in the import graph: this
file needs the monoid, not the panel, so it imports `Agentic.Monoid` and the
edge `Trace → Panel` — which existed only to reach `PMonoid` and pointed the
wrong way, a concurrency object depending on a fan-in construction that ought
to depend on it — is gone.
-/

namespace Agentic

section Traces

variable {A : Type} {ind : A → A → Prop}

/-- A `Swap ind u v` is a representation of *one* rescheduling step: two
adjacent turns that are independent of one another are exchanged, and nothing
else about the history changes. The independence relation `ind` is the design
input — it says which pairs of turns do not observe each other — and it is
supplied per alphabet, not fixed here. Symmetry of `ind` is not assumed: the
congruence generated below makes the relation symmetric regardless.

This is the module's whole input to Mathlib's machinery: `conGen` closes it
under reflexivity, symmetry, transitivity *and* multiplication on both sides,
so the congruence lemmas the package used to prove by list surgery are not
needed. -/
inductive Swap (ind : A → A → Prop) : List A → List A → Prop
  /-- Exchange the adjacent independent turns `a` and `b` in the context
  `u ++ · ++ v`. -/
  | swap {u v : List A} {a b : A} : ind a b → Swap ind (u ++ a :: b :: v) (u ++ b :: a :: v)

/-- The congruence on schedules generated by rescheduling: Mathlib's `conGen`
at `Swap`, over the free monoid `FreeMonoid A` of schedules. A congruence
rather than a mere equivalence is what makes concatenation well defined on the
classes, and Mathlib both generates it and proves it a congruence. -/
def traceCon (ind : A → A → Prop) : Con (FreeMonoid A) :=
  conGen (M := FreeMonoid A) (Swap ind)

/-- A `TraceEqv ind u v` is a representation of *`u` and `v` are the same
history*: one can be turned into the other by finitely many exchanges of
adjacent independent turns, in any context. It is Mathlib's `ConGen.Rel` at
`Swap ind` — the inductively generated congruence, whose constructors are
`of`, `refl`, `symm`, `trans` and `mul` — under the package's name. -/
abbrev TraceEqv (ind : A → A → Prop) (u v : FreeMonoid A) : Prop :=
  ConGen.Rel (M := FreeMonoid A) (Swap ind) u v

/-- One rescheduling step is a rescheduling (`ConGen.Rel.of`, under the
package's old constructor name). -/
theorem TraceEqv.step {u v : List A} (h : Swap ind u v) : TraceEqv ind u v :=
  ConGen.Rel.of (M := FreeMonoid A) u v h

/-- A history is itself (`ConGen.Rel.refl`). -/
theorem TraceEqv.refl (u : List A) : TraceEqv ind u u :=
  ConGen.Rel.refl (M := FreeMonoid A) u

/-- Rescheduling is reversible (`ConGen.Rel.symm`). -/
theorem TraceEqv.symm {u v : List A} (h : TraceEqv ind u v) : TraceEqv ind v u :=
  ConGen.Rel.symm (M := FreeMonoid A) h

/-- Reschedulings compose (`ConGen.Rel.trans`). -/
theorem TraceEqv.trans {u v w : List A} (h₁ : TraceEqv ind u v) (h₂ : TraceEqv ind v w) :
    TraceEqv ind u w :=
  ConGen.Rel.trans (M := FreeMonoid A) h₁ h₂

/-- Prefixing a common history preserves sameness of histories: the left
congruence of `append`. It used to be an induction over the generated
equivalence resting on a list-surgery lemma about `Swap`; a congruence is
closed under multiplication by construction, so it is now one application of
`ConGen.Rel.mul`. -/
theorem TraceEqv.append_left {u v : List A} (w : List A) (h : TraceEqv ind u v) :
    TraceEqv ind (w ++ u) (w ++ v) :=
  ConGen.Rel.mul (M := FreeMonoid A) (TraceEqv.refl w) h

/-- Appending a common suffix preserves sameness of histories: the right
congruence of `append`, likewise `ConGen.Rel.mul`. -/
theorem TraceEqv.append_right {u v : List A} (w : List A) (h : TraceEqv ind u v) :
    TraceEqv ind (u ++ w) (v ++ w) :=
  ConGen.Rel.mul (M := FreeMonoid A) h (TraceEqv.refl w)

/-- A `Trace ind` is a representation of an *interaction history up to
scheduling*: a sequence of turns in which independent adjacent turns may be
exchanged freely, and dependent ones may not. It is the free partially
commutative (Mazurkiewicz) monoid on the alphabet `A`, built as Mathlib's
quotient of `FreeMonoid A` by the congruence `traceCon ind`.

Taking the quotient — rather than carrying lists plus a "these are equivalent"
predicate — is the point. A meaning defined on `Trace ind` *cannot* observe
the order of independent turns: the type makes the invariance a theorem about
the meaning space instead of a discipline on its users. -/
def Trace {A : Type} (ind : A → A → Prop) : Type := (traceCon ind).Quotient

namespace Trace

/-- The history denoted by a concrete schedule: the class of the list `u`. -/
def mk (u : List A) : Trace ind := Quotient.mk'' (u : FreeMonoid A)

/-- The one-turn history. -/
def single (a : A) : Trace ind := mk [a]

/-- The empty history: no turns have been taken. It is the monoid's `1`
(`one_eq_mk`), kept as a name of its own. -/
def one : Trace ind := mk []

/-- **Histories combine, and this is the package's monoid.** Concatenation of
histories is `⋄` and the empty history is `PMonoid.unit`.

The three laws are no longer proved here: the quotient of a monoid by a
congruence is a monoid, which is Mathlib's `Con.monoid`, and the instance below
is that one transported along `Trace`'s definition. The three theorems that
follow are one-line readings of Mathlib's fields, kept under their old names.

Its point is that the *key* of a panel may be a history up to scheduling: the
weight of a session is then indexed by what happened, with independent turns
already identified. That instantiation was unavailable while `MSemiring`
demanded `DecidableEq` of its keys, since equality of traces is equality of
classes of a quotient by a generated congruence and no one is going to decide
it (acat-192). -/
instance instPMonoid : Monoid (Trace ind) :=
  inferInstanceAs (Monoid (traceCon ind).Quotient)

/-- Concatenation of histories: take the turns of the first, then those of the
second. It is well defined on classes because `traceCon ind` is a *congruence*
— Mathlib's `conGen` closes `Swap` under multiplication on both sides — so the
two nested `Quot.lift`s the package used to write are `Con`'s. -/
abbrev mul (x y : Trace ind) : Trace ind := x * y

/-- The key operation on histories is concatenation, definitionally. -/
theorem op_eq_mul (x y : Trace ind) : x ⋄ y = Trace.mul x y := rfl

/-- Concatenation of classes is the class of the concatenation: the defining
computation rule of `⋄` on traces, and the only fact about it later proofs
need. It is Mathlib's `Con.coe_mul`, which is `rfl`. -/
theorem mk_mul_mk (u v : List A) : (mk u : Trace ind) ⋄ mk v = mk (u ++ v) := rfl

/-- The empty history is the class of the empty schedule. -/
theorem one_eq_mk : (1 : Trace ind) = mk [] := rfl

/-- A one-turn history is the class of the one-element schedule. -/
theorem single_eq_mk (a : A) : (single a : Trace ind) = mk [a] := rfl

/-- Concatenation of histories is unbracketed: a history has no grouping (the
monoid field, in notation). -/
theorem mul_assoc (x y z : Trace ind) : x ⋄ y ⋄ z = x ⋄ (y ⋄ z) :=
  _root_.mul_assoc x y z

/-- The empty history is a left unit: starting from nothing changes nothing. -/
theorem one_mul (x : Trace ind) : 1 ⋄ x = x :=
  _root_.one_mul x

/-- The empty history is a right unit: continuing with nothing changes
nothing. -/
theorem mul_one (x : Trace ind) : x ⋄ 1 = x :=
  _root_.mul_one x

/-- Independent turns commute.

Which schedules are EQUAL is chosen here: independent turns commute, dependent
ones do not — the panel's permutation invariance and the pipeline's
order-sensitivity in one object. The proof is soundness of the quotient
(`Quot.sound`) at a single adjacent transposition with empty context on both
sides; everything else about the quotient exists to make this one equation true
without making any other equation true. -/
theorem indep_comm {a b : A} (h : ind a b) :
    (single a : Trace ind) ⋄ single b = single b ⋄ single a :=
  Quot.sound (ConGen.Rel.of (M := FreeMonoid A) _ _ (Swap.swap (u := []) (v := []) h))

/-- With no independence at all, rescheduling is equality: the quotient
collapses to lists. This is the negative half of the design claim — the
quotient identifies independent schedules and *nothing else*. The `mul` case is
the one Mathlib's generated congruence adds over a bare equivalence, and it is
discharged by congruence of `append`. -/
theorem eq_of_traceEqv_of_indep_empty (hind : ∀ a b : A, ¬ ind a b)
    {u v : List A} (h : TraceEqv ind u v) : u = v := by
  induction h with
  | of _ _ hs => cases hs with | swap hab => exact absurd hab (hind _ _)
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | mul _ _ ih₁ ih₂ => exact congrArg₂ (· ++ ·) ih₁ ih₂

/-- Dependent turns really do not commute: when nothing is independent,
distinct turns denote distinct orders. Without this the previous theorem could
be satisfied by a quotient that identified everything, and "order matters"
would be a claim about notation rather than about meaning.

Exactness of the quotient — that equal classes come from related schedules — is
Mathlib's `Quotient.exact`, where the package used to build the retraction by
hand with a `Quot.lift`. -/
theorem single_mul_single_ne_of_indep_empty (hind : ∀ a b : A, ¬ ind a b)
    {a b : A} (hab : a ≠ b) :
    (single a : Trace ind) ⋄ single b ≠ single b ⋄ single a := by
  intro h
  have h1 : TraceEqv ind [a, b] [b, a] := Quotient.exact h
  have h2 : [a, b] = [b, a] := eq_of_traceEqv_of_indep_empty hind h1
  injection h2 with h3 _
  exact hab h3

end Trace

/-- A `Session S ind` is a representation of a semiring-valued judgment of
every possible interaction history: it assigns to each trace — each history up
to scheduling — a resource in `S`. Over `Prop` it is the set of admissible
histories, over `Cost` the worst-case budget of reaching one, over an
expectation semiring its measure. Because the domain is the quotient, a
session cannot distinguish two schedules that differ only in the order of
independent turns; the invariance is structural, not asserted. -/
def Session (S : Type) [CompleteCSemiring S] {A : Type} (ind : A → A → Prop) : Type :=
  Trace ind → S

variable {S : Type} [CompleteCSemiring S]

/-- The Brzozowski derivative of a session by a prefix: what the session says
about everything that can still happen once `u` has happened.

Fork and resume are the same operation: continue the session past a prefix. A
fork hands the continuation `deriv u f` to another agent; a resume evaluates
it later; a cache stores it.

**Continuing past a prefix IS the left action of a monoid on a reader** —
`actL` of `Agentic.Monoid`, at no distance whatever, exactly as entering a
scope is `actR`. The two laws below are that action's two laws, imported
rather than reproved; what is specific to sessions is the monoid, which is the
trace monoid, and not the action. -/
def deriv (u : Trace ind) (f : Session S ind) : Session S ind :=
  actL u f

/-- Continuing past nothing is not continuing: the empty prefix acts trivially
(`actL_unit`). -/
theorem deriv_one (f : Session S ind) : deriv (1 : Trace ind) f = f :=
  actL_unit f

/-- Continuing past `u ⋄ v` is continuing past `u` and then past `v`: the
derivative is a monoid action (contravariantly composed, which is what makes
resume-after-fork associate). It is `actL_compose`, and the reversal of the
operands against `withScope_compose` is the difference between the two
actions. -/
theorem deriv_mul (u v : Trace ind) (f : Session S ind) :
    deriv (u ⋄ v) f = deriv v (deriv u f) :=
  actL_compose u v f

/-- Independent turns are indistinguishable to *every* session: the
permutation invariance of a panel, transported to judgments. This is the
payoff of quotienting — it is a theorem about all meanings at once, with no
hypothesis on the session. -/
theorem deriv_indep_comm {a b : A} (h : ind a b) (f : Session S ind) :
    deriv (Trace.single a ⋄ Trace.single b) f
      = deriv (Trace.single b ⋄ Trace.single a) f := by
  rw [Trace.indep_comm h]

end Traces

end Agentic
