{-# LANGUAGE OverloadedStrings #-}

-- | Versioned relational coordination facts. Stored identities are not capabilities.
module Agentic.Manager.Schema (schemaVersion, schemaStatements, commandMigration) where

import Data.Text (Text)

schemaVersion :: Int
schemaVersion = 2

schemaStatements :: [Text]
schemaStatements =
  [ "CREATE TABLE service_metadata (singleton INTEGER PRIMARY KEY CHECK(singleton=1), authority_epoch TEXT NOT NULL UNIQUE, stream_id TEXT NOT NULL UNIQUE, sequence TEXT NOT NULL CHECK(length(sequence) BETWEEN 1 AND 20 AND sequence NOT GLOB '*[^0-9]*' AND (sequence='0' OR substr(sequence,1,1) BETWEEN '1' AND '9') AND (length(sequence)<20 OR sequence<='18446744073709551615')), retained_floor TEXT NOT NULL CHECK(length(retained_floor) BETWEEN 1 AND 20 AND retained_floor NOT GLOB '*[^0-9]*' AND (retained_floor='0' OR substr(retained_floor,1,1) BETWEEN '1' AND '9') AND (length(retained_floor)<20 OR retained_floor<='18446744073709551615')), revision TEXT NOT NULL) STRICT",
    "CREATE TABLE clients (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, authorization_revision TEXT NOT NULL, retired INTEGER NOT NULL DEFAULT 0 CHECK(retired IN (0,1))) STRICT",
    "CREATE TABLE credentials (id TEXT PRIMARY KEY NOT NULL, client_id TEXT NOT NULL REFERENCES clients(id), verifier BLOB NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked INTEGER NOT NULL CHECK(revoked IN (0,1))) STRICT",
    "CREATE TABLE credential_scopes (credential_id TEXT NOT NULL REFERENCES credentials(id), profile_id TEXT NOT NULL, scope TEXT NOT NULL CHECK(scope IN ('observe','submit','control','export')), PRIMARY KEY(credential_id,profile_id,scope)) STRICT",
    "CREATE TABLE requests (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, client_id TEXT NOT NULL REFERENCES clients(id), workflow_id TEXT NOT NULL, descriptor_revision TEXT NOT NULL, profile_id TEXT NOT NULL, profile_revision TEXT NOT NULL, phase TEXT NOT NULL CHECK(phase IN ('draft','queued','preparing','review','start-pending','associated','withdrawn','refused')), admission TEXT NOT NULL CHECK(admission IN ('not-queued','waiting','reserved','released','refused')), queue_ordinal TEXT UNIQUE, blocking_reasons BLOB NOT NULL, validation_errors BLOB NOT NULL, parent_run_id TEXT REFERENCES runs(id), lineage_operation TEXT CHECK(lineage_operation IN ('restart','resume','fork')), lineage_edits BLOB, UNIQUE(id,profile_id), CHECK((parent_run_id IS NULL)=(lineage_operation IS NULL))) STRICT",
    "CREATE TABLE captures (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, request_id TEXT NOT NULL REFERENCES requests(id), client_id TEXT NOT NULL REFERENCES clients(id), profile_id TEXT NOT NULL, private_reference BLOB NOT NULL UNIQUE, bytes INTEGER NOT NULL CHECK(bytes BETWEEN 0 AND 67108864), sha256 TEXT NOT NULL CHECK(length(sha256)=64), UNIQUE(id,request_id), FOREIGN KEY(request_id,profile_id) REFERENCES requests(id,profile_id)) STRICT",
    "CREATE TABLE request_inputs (request_id TEXT NOT NULL REFERENCES requests(id), name TEXT NOT NULL, declaration_ordinal INTEGER NOT NULL CHECK(declaration_ordinal BETWEEN 0 AND 255), declaration BLOB NOT NULL, source TEXT CHECK(source IN ('literal','capture')), literal BLOB, capture_id TEXT, FOREIGN KEY(capture_id,request_id) REFERENCES captures(id,request_id), PRIMARY KEY(request_id,name), UNIQUE(request_id,declaration_ordinal), CHECK((source IS NULL AND literal IS NULL AND capture_id IS NULL) OR (source IS 'literal' AND literal IS NOT NULL AND capture_id IS NULL) OR (source IS 'capture' AND literal IS NULL AND capture_id IS NOT NULL))) STRICT",
    "CREATE TABLE reservations (id TEXT PRIMARY KEY NOT NULL, request_id TEXT NOT NULL REFERENCES requests(id), slot INTEGER UNIQUE CHECK(slot BETWEEN 0 AND 15), process_generation TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('held','cleanup-pending','quarantined','released')), CHECK((slot IS NULL)=(state='released')), UNIQUE(id,request_id)) STRICT",
    "CREATE UNIQUE INDEX one_active_reservation ON reservations(request_id) WHERE state!='released'",
    "CREATE TABLE reservation_resources (resource_key TEXT PRIMARY KEY NOT NULL, reservation_id TEXT NOT NULL REFERENCES reservations(id)) STRICT",
    "CREATE TRIGGER release_without_claims BEFORE UPDATE OF state ON reservations WHEN NEW.state='released' AND EXISTS(SELECT 1 FROM reservation_resources WHERE reservation_id=OLD.id) BEGIN SELECT RAISE(ABORT,'reservation retains resource claims'); END",
    "CREATE TRIGGER claim_active_reservation BEFORE INSERT ON reservation_resources WHEN (SELECT state FROM reservations WHERE id=NEW.reservation_id)='released' BEGIN SELECT RAISE(ABORT,'reservation is released'); END",
    "CREATE TRIGGER move_claim_to_active_reservation BEFORE UPDATE OF reservation_id ON reservation_resources WHEN (SELECT state FROM reservations WHERE id=NEW.reservation_id)='released' BEGIN SELECT RAISE(ABORT,'reservation is released'); END",
    "CREATE TABLE preparations (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, request_id TEXT NOT NULL REFERENCES requests(id), request_revision TEXT NOT NULL, profile_revision TEXT NOT NULL, reservation_id TEXT NOT NULL REFERENCES reservations(id), process_generation TEXT NOT NULL, worker_identity TEXT NOT NULL, root_identity TEXT NOT NULL, native_run_id TEXT NOT NULL, expires_at TEXT NOT NULL, review_digest TEXT NOT NULL, review BLOB NOT NULL, private_binding BLOB NOT NULL, state TEXT NOT NULL CHECK(state IN ('live','consumed','invalidated')), reason TEXT CHECK(reason IN ('expired','input-changed','profile-changed','worker-lost','discarded','authority-changed','consumed')), UNIQUE(id,request_id), FOREIGN KEY(reservation_id,request_id) REFERENCES reservations(id,request_id)) STRICT",
    "CREATE UNIQUE INDEX one_live_preparation ON preparations(request_id) WHERE state='live'",
    "CREATE TABLE preparation_captures (preparation_id TEXT NOT NULL REFERENCES preparations(id), capture_id TEXT NOT NULL REFERENCES captures(id), PRIMARY KEY(preparation_id,capture_id)) STRICT",
    "CREATE TABLE runs (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, control_revision TEXT NOT NULL, request_id TEXT UNIQUE REFERENCES requests(id), preparation_id TEXT UNIQUE REFERENCES preparations(id), profile_id TEXT NOT NULL, root_identity TEXT NOT NULL, native_run_id TEXT NOT NULL, parent_run_id TEXT REFERENCES runs(id), supervision TEXT NOT NULL CHECK(supervision IN ('owned','cleanup-pending','lost','observer')), runtime_snapshot BLOB, snapshot_version INTEGER, result_state TEXT NOT NULL CHECK(result_state IN ('absent','referenced','verified','unavailable')), result_artifact_id TEXT REFERENCES artifacts(id), UNIQUE(profile_id,root_identity,native_run_id), FOREIGN KEY(preparation_id,request_id) REFERENCES preparations(id,request_id), FOREIGN KEY(result_artifact_id,id) REFERENCES artifacts(id,run_id), CHECK((runtime_snapshot IS NULL)=(snapshot_version IS NULL))) STRICT",
    "CREATE TABLE ingestions (run_id TEXT NOT NULL REFERENCES runs(id), sequence TEXT NOT NULL CHECK(length(sequence) BETWEEN 1 AND 20 AND sequence NOT GLOB '*[^0-9]*' AND (sequence='0' OR substr(sequence,1,1) BETWEEN '1' AND '9') AND (length(sequence)<20 OR sequence<='18446744073709551615')), envelope_digest TEXT NOT NULL, envelope BLOB NOT NULL, PRIMARY KEY(run_id,sequence)) STRICT",
    "CREATE TABLE commands (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, profile_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('create','capture','set-input','remove-input','enqueue','withdraw','approve','discard','cancel','steer','retry','choose-recovery','redirect','answer','export','restart','resume','fork')), client_id TEXT NOT NULL REFERENCES clients(id), authority_epoch TEXT NOT NULL, method TEXT NOT NULL CHECK(method='POST'), resource_uri TEXT NOT NULL, idempotency_key TEXT NOT NULL, body BLOB, media_type TEXT, precondition TEXT, receipt BLOB, retired INTEGER NOT NULL CHECK(retired IN (0,1)), request_id TEXT REFERENCES requests(id), run_id TEXT REFERENCES runs(id), preparation_id TEXT REFERENCES preparations(id), decision_id TEXT REFERENCES decisions(id), accepted_at TEXT NOT NULL, dispatch_generation TEXT, attempted_at TEXT, acknowledgement BLOB, effect_evidence BLOB, state TEXT NOT NULL CHECK(state IN ('accepted','dispatch-attempted','acknowledged','effect-observed','refused','unresolved')), UNIQUE(client_id,method,resource_uri,idempotency_key), CHECK(retired=0 OR (body IS NULL AND media_type IS NULL AND precondition IS NULL AND receipt IS NULL))) STRICT",
    "CREATE TABLE command_captures (command_id TEXT NOT NULL REFERENCES commands(id), capture_id TEXT NOT NULL REFERENCES captures(id), PRIMARY KEY(command_id,capture_id)) STRICT",
    "CREATE TABLE decisions (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES runs(id), occurrence_id TEXT NOT NULL, attempt_id TEXT, generation TEXT NOT NULL, observed_sequence TEXT NOT NULL CHECK(length(observed_sequence) BETWEEN 1 AND 20 AND observed_sequence NOT GLOB '*[^0-9]*' AND (observed_sequence='0' OR substr(observed_sequence,1,1) BETWEEN '1' AND '9') AND (length(observed_sequence)<20 OR observed_sequence<='18446744073709551615')), kind TEXT NOT NULL CHECK(kind IN ('question','recovery')), state TEXT NOT NULL CHECK(state IN ('pending','submitting','resolved','invalidated')), question_artifact_id TEXT REFERENCES artifacts(id), recovery_options BLOB, command_id TEXT UNIQUE REFERENCES commands(id), UNIQUE(run_id,occurrence_id,attempt_id,generation,kind), FOREIGN KEY(question_artifact_id,run_id) REFERENCES artifacts(id,run_id)) STRICT",
    "CREATE UNIQUE INDEX decision_identity ON decisions(run_id,occurrence_id,coalesce(attempt_id,''),generation,kind)",
    "CREATE TABLE artifacts (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES runs(id), private_reference BLOB NOT NULL, code BLOB NOT NULL, verification TEXT NOT NULL CHECK(verification IN ('referenced','verified','unavailable')), verification_failure TEXT, UNIQUE(run_id,private_reference), UNIQUE(id,run_id)) STRICT",
    "CREATE TABLE exports (id TEXT PRIMARY KEY NOT NULL, revision TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES runs(id), artifact_id TEXT NOT NULL REFERENCES artifacts(id), command_id TEXT NOT NULL UNIQUE REFERENCES commands(id), destination_root_identity TEXT NOT NULL, name TEXT NOT NULL, expected_sha256 TEXT NOT NULL, receipt BLOB, state TEXT CHECK(state IN ('published','unresolved')), UNIQUE(destination_root_identity,name), FOREIGN KEY(artifact_id,run_id) REFERENCES artifacts(id,run_id)) STRICT",
    "CREATE TABLE invalidations (stream_id TEXT NOT NULL REFERENCES service_metadata(stream_id), sequence TEXT NOT NULL CHECK(length(sequence) BETWEEN 1 AND 20 AND sequence NOT GLOB '*[^0-9]*' AND (sequence='0' OR substr(sequence,1,1) BETWEEN '1' AND '9') AND (length(sequence)<20 OR sequence<='18446744073709551615')), kind TEXT NOT NULL CHECK(kind IN ('request.changed','preparation.changed','run.changed','decision.changed','command.changed','artifact.changed','service.changed')), resource_uri TEXT NOT NULL, revision TEXT NOT NULL, PRIMARY KEY(stream_id,sequence)) STRICT",
    "CREATE INDEX replay_order ON invalidations(stream_id,length(sequence),sequence)"
  ]

-- | Version-two ledger additions. Version-one records and original receipts survive.
commandMigration :: [Text]
commandMigration =
  [ "ALTER TABLE commands ADD COLUMN body_sha256 BLOB CHECK(body_sha256 IS NULL OR length(body_sha256)=32)",
    "ALTER TABLE commands ADD COLUMN refusal TEXT CHECK(refusal IN ('state-conflict','stale-revision','unsupported-operation','ownership-unavailable','supervision-unavailable','invalid-answer','invalid-lineage-edit','export-conflict','storage-unavailable'))",
    "ALTER TABLE commands ADD COLUMN body_bytes INTEGER CHECK(body_bytes IS NULL OR body_bytes BETWEEN 0 AND 67108864)",
    "ALTER TABLE commands ADD COLUMN reserved_bytes INTEGER NOT NULL DEFAULT 131072 CHECK(reserved_bytes BETWEEN 0 AND 131072)",
    "CREATE TABLE command_ledger_usage (singleton INTEGER PRIMARY KEY CHECK(singleton=1), bytes INTEGER NOT NULL CHECK(bytes>=0)) STRICT",
    "INSERT INTO command_ledger_usage SELECT 1,coalesce(sum(reserved_bytes+coalesce(length(body),0)),0) FROM commands",
    "CREATE TRIGGER command_charge_insert AFTER INSERT ON commands BEGIN UPDATE command_ledger_usage SET bytes=bytes+NEW.reserved_bytes+coalesce(length(NEW.body),0) WHERE singleton=1; END",
    "CREATE TRIGGER command_charge_update AFTER UPDATE OF reserved_bytes,body ON commands BEGIN UPDATE command_ledger_usage SET bytes=bytes+NEW.reserved_bytes+coalesce(length(NEW.body),0)-OLD.reserved_bytes-coalesce(length(OLD.body),0) WHERE singleton=1; END",
    "CREATE TRIGGER command_replay_protection BEFORE DELETE ON commands BEGIN SELECT RAISE(ABORT,'command replay protection is retained'); END",
    "CREATE TABLE command_ordinary_rate (credential_id TEXT PRIMARY KEY NOT NULL REFERENCES credentials(id), minute INTEGER NOT NULL, count INTEGER NOT NULL CHECK(count>=0)) STRICT",
    "CREATE TABLE command_safety_rate (singleton INTEGER PRIMARY KEY CHECK(singleton=1), minute INTEGER NOT NULL, count INTEGER NOT NULL CHECK(count>=0)) STRICT",
    "INSERT INTO command_safety_rate VALUES (1,0,0)"
  ]
